name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.0
      with:
        lein: 2.11.2
          
    - name: Cache deps
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
        restore-keys: |
              ${{ runner.os }}-maven-

    - name: Fetch deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        lein deps

    - name: Run tests
      env: 
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        FIREBASE_CONFIG: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        FIREBASE_API: ${{ secrets.FIREBASE_API }}    
      run: |
        lein cloverage --codecov
        bash <(curl -s https://codecov.io/bash)
